name: classification
on: 
  pull_request:
    branches:
      - main
    paths:
      - "*" 
jobs:
  classification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.ref }}
        - name: Build container
          run: |
            docker build -t classification .
        - name: Configure AWS Credential
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Push2ECR
          uses: jwalton/gh-ecr-push@v1
          with: 
            access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            region: us-east-1
            image: classification
        - name: Update lambda with image
          run: aws lambda update-function-code --function-name  classification --image-uri 968911158010.dkr.ecr.us-east-1.amazonaws.com/classification:latest
